name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey there! Thanks for contributing to project Halcyon, make sure you have read the LICENSE and the community guidelines. Furthermore, make sure to check over your submission and make sure there are no discrepancies. Thank you very much :)"
